services:
  judge-server:
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    container_name: judge-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/app
      - ./resource:/resource
      - /sys/fs/cgroup:/sys-host/fs/cgroup # Windows, MacOSだとこれ意味ない
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
  
  mysql:
    image: mysql:9.0
    container_name: judge-mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: judge
      MYSQL_DATABASE: task
      MYSQL_USER: judge
      MYSQL_PASSWORD: judge
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
volumes:
  mysql-data:
