version: '3.8'

services:
  judge-server:
    build: .
    container_name: judge-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
